version: 2

seeds:
  - name: product_subcategory
    config:
      schema: production
      column_types:
        product_subcategory_id: integer
        product_category_id: integer
        name: string
        modified_date: timestamp
